message:
  passphrase: "Kans4s-i$-g01ng-by3-bye"
  valid_node_names:
    - alpha
    - beta
    - gamma
    - delta
    - theta
    - lambda
    - tau
    - psi
    - omega
  sources:
    - name: sentinels
      url: http://challenge.distribusion.com/the_one/routes?source=sentinels
    - name: sniffers
      url: http://challenge.distribusion.com/the_one/routes?source=sniffers
    - name: loopholes
      url: http://challenge.distribusion.com/the_one/routes?source=loopholes
  destination:
    url: https://challenge.distribusion.com/the_one/routes
